### ISSUE TITLE
请教如何文章置顶

### ISSUE THREAD

**Issue by SuperDannyDeveloper** [nooldey/hexo-theme-yilia#1]
你好，很高兴看到你所修改的yilia主题，本人遇到一个问题，就是关于文章该如何置顶的问题，想请教一下。谢谢。

**Comment by nooldey** [comment]
@SuperDannyDeveloper  抱歉，刚看到您的留言。文章置顶这样做：在文章metter 标注 'top: true'即可。

``` HTML
    title: 
    tags:
    categories:
    top: true
    date: 
```

**Comment by SuperDannyDeveloper** [comment]
@nooldey 非常感谢

**Comment by SuperDannyDeveloper** [comment]
@nooldey 刚刚试了下，貌似没效果

**Comment by nooldey** [comment]
@SuperDannyDeveloper  把我的主题复制过去试试。注意备份你的个人设置文件

**Comment by SuperDannyDeveloper** [comment]
@nooldey 复制过了。不能置顶。我是这样设置的

```
    title: 栏目
    status: public
    tags: [栏目]
    top: 
     - true
    date: 2015-06-06 06:06
```
